export OS_AUTH_URL=http://<YOUR KEYSTONE IP, LIKELY TO BE YOUR LOCAL IPS IF YOU ARE RUNNING DEVSTACK>:5000/v2.0
export OS_USERNAME=admin
export OS_PASSWORD=simple
export OS_REGION_NAME=RegionOne
export OS_TENANT_NAME=admin
